### ISSUE TITLE
1.8.9 Paper: false positive FlightC

### ISSUE THREAD

**Issue by F3F5** [tiredvekster/LightAntiCheat#7]
![2024-07-10_18 04 16](https://github.com/tiredvekster/LightAntiCheat/assets/170719238/1446c669-9ef6-4f72-a4ef-dd4e392b4adb)
1.8.9 Paper: false positive FlightC
Version: 1.2.5

**Comment by F3F5** [comment]
https://github.com/tiredvekster/LightAntiCheat/assets/170719238/2f4b7f46-8b61-4ec0-9058-221cc0bff4a9

**Comment by tiredvekster** [comment]
Hi! Thanks for attaching the video. I'll try to fix the false positive in the next update. 1.8.8 is the MC version that I find most difficult to support, as Light's native version is 1.20.

**Comment by tiredvekster** [comment]
Hello! Hopefully, this false positive has been fixed in LAC 1.2.6.
