### ISSUE TITLE
1.21 Paper - Ladder FastClimb false positives

### ISSUE THREAD

**Issue by axtonprice** [tiredvekster/LightAntiCheat#9]
Server: MC 1.21 PaperMC #89
Version: 1.2.5

Spamming Sneak + W whilst on a ladder causes false positives for FastClimb detection. The same applies when sneaking on a ladder and moving slowly upwards every 1 - 1.5 seconds.
The anticheat also falsely flags when brushing up against a ladder but not climbing it.

https://github.com/user-attachments/assets/15f8909b-11cc-46f4-8371-a9d6c8038c5d

https://github.com/user-attachments/assets/49205adc-14b1-455c-a4af-446ea8dddf19

(Not related to my client-side perspective mod)

**Comment by tiredvekster** [comment]
Hello there! The false positive has been fixed in LAC 1.2.6.
